### ISSUE TITLE
Is it possible to Update a Property?

### ISSUE THREAD

**Issue by dawwa** [andrewjpoole/jsonelement.extensions#2]
I'm trying to add a method for updating a property, e.g., below, but seems like this does not work, the property does not get created, and even it works, it would not be an in place update, instead, it tries to remove and then add, which will results in the property order gets changes, and has performance impacts per https://stackoverflow.com/questions/29493292/newtonsoft-json-net-deserialization-error-where-fields-in-json-change-order

Do you know some way to get an in place update if the property already exists? 

```csharp
        public static JsonElement UpdateProperty(this JsonElement jElement, string name, object value, JsonSerializerOptions options = null)
        {
            if (jElement.TryGetProperty(name, out JsonElement e))
            {
                jElement = jElement.RemoveProperty(name);
            }

            jElement = jElement.AddProperty(name, value, options);

            return jElement;
        }
```

**Comment by andrewjpoole** [comment]
Hi Dawwa, interesting question, I think that SO question is quite old and related to both WCF and Newtonsoft JSON.net so I'm not sure how those technologies fit in with the new System.Text.Json APIs that this repo/package relates to.
However, I would like to be able to support preserving the order of properties and also Insert at an index etc.
I'm trying out a few ideas, but want to do some benchmarking to make sure performance doesn't suffer.

**Comment by dawwa** [comment]
@andrewjpoole , I managed to make the following worked, but did not figure out how to update a nested property with a given path, seems like a recursive might be involved...

```csharp
        public static JsonElement UpdateProperty(this JsonElement jElement, string propertyName, object propertyValue, JsonSerializerOptions options = null)
        {
            if (jElement.ValueKind != JsonValueKind.Object)
                throw new Exception("Only able to add properties to json objects (i.e. jElement.ValueKind == JsonValueKind.Object)");

            var arrayBufferWriter = new ArrayBufferWriter<byte>();
            using (var utf8JsonWriter1 = new Utf8JsonWriter(arrayBufferWriter))
            {
                utf8JsonWriter1.WriteStartObject();

                var namesOfPropertiesToRemove = new List<string>();

                foreach (var jProp in jElement.EnumerateObject())
                {
                    if (jProp.NameEquals(propertyName))
                    {
                        utf8JsonWriter1.WritePropertyName(propertyName);
                        RenderValue(utf8JsonWriter1, propertyValue, options);
                    }
                    else
                    {
                        jProp.WriteTo(utf8JsonWriter1);
                    }
                }
                utf8JsonWriter1.WriteEndObject();
            }
            var resultJson = Encoding.UTF8.GetString(arrayBufferWriter.WrittenSpan);
            return JsonDocument.Parse(resultJson, new JsonDocumentOptions
            {
                AllowTrailingCommas = true,
                CommentHandling = JsonCommentHandling.Skip,
                MaxDepth = 9999
            }).RootElement;
        }
```

**Comment by andrewjpoole** [comment]
Hey there, check out version 1.5 it adds support for UpdateProperty and InsertProperty which preserve the original order of the properties
